### ISSUE TITLE
Add 4th and 5th channel for dual-white strip

### ISSUE THREAD

**Issue by renne** [tjclement/esp-dimmer-hardware#10] opened 2018-04-12 10:32 UTC
The [CRI-value](https://en.wikipedia.org/wiki/Color_rendering_index) of RGB-stripes is quite low. I suggest to add a 4th and 5th channel for a dual-white LED-strip.

**Comment by tjclement** [comment] 2018-04-12 10:34
Duplicate of #8, closing this one

**Closed as completed by tjclement** 2018-04-12 10:34 UTC
Labels: duplicate
